name: platzi_repository
description: My new Flutter package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platzi_api:
    path: "../platzi_api"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
